### ISSUE TITLE
Type `getSignalQuarity()`

### ISSUE THREAD

**Issue by key** [sakuraio/SakuraIOArduino#21]
I found a typo.
Name of `getSignalQuarity() ` is seems to wrong. `Quality` is correct. (*L*)

https://github.com/sakura-internet/SakuraIOArduino/blob/master/src/SakuraIO.h#L26

**Comment by chibiegg** [comment]
OMG 😱

**Comment by chibiegg** [comment]
Fixed in v1.0.3. Thanks a lot.

Old function `getSignalQuarity()` is left for compatibility. 😭
